"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 23:33:55.962441
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_kind'), ['kind'], unique=False)

    op.create_table('firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=False),
    sa.Column('payout_classification', sa.String(length=32), nullable=False),
    sa.Column('payout', sa.JSON(), nullable=False),
    sa.Column('jurisdiction', sa.JSON(), nullable=False),
    sa.Column('kyc', sa.JSON(), nullable=False),
    sa.Column('automation', sa.JSON(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('risk_signals', sa.JSON(), nullable=False),
    sa.Column('unknowns', sa.JSON(), nullable=False),
    sa.Column('researched_at', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firms_slug'), ['slug'], unique=True)

    op.create_table('kill_switches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_by', sa.String(length=80), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kill_switches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kill_switches_account_id'), ['account_id'], unique=False)

    op.create_table('ledger_positions',
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('position_id', sa.String(length=80), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('account_id', 'position_id')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=60), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_input_hash'), ['input_hash'], unique=False)

    op.create_table('orders',
    sa.Column('client_order_id', sa.String(length=80), nullable=False),
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('client_order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('processed_events',
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('account_id', 'event_id')
    )
    op.create_table('risk_states',
    sa.Column('account_id', sa.String(length=80), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('trade_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('account_size', sa.Float(), nullable=False),
    sa.Column('trades', sa.JSON(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_accounts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('firm_slug', sa.String(length=80), nullable=False),
    sa.Column('program_slug', sa.String(length=120), nullable=False),
    sa.Column('phase', sa.String(length=40), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('adapter', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('live_approved', sa.Boolean(), nullable=False),
    sa.Column('live_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('live_approval_fingerprint', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('citizenship', sa.String(length=2), nullable=False),
    sa.Column('residence_country', sa.String(length=2), nullable=True),
    sa.Column('residence_region', sa.String(length=80), nullable=True),
    sa.Column('tax_residency', sa.String(length=2), nullable=True),
    sa.Column('kyc_documents', sa.JSON(), nullable=False),
    sa.Column('ip_location_country', sa.String(length=2), nullable=True),
    sa.Column('payout_requirement', sa.String(length=32), nullable=False),
    sa.Column('preferred_networks', sa.JSON(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('automation_channel', sa.String(length=10), nullable=False),
    sa.Column('max_budget_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_version'), ['version'], unique=False)

    op.create_table('wallet_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('confirmed_by_owner', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=80), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)

    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=200), nullable=False),
    sa.Column('rule_kind', sa.String(length=60), nullable=True),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_firm_id'), ['firm_id'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('refund', sa.Text(), nullable=False),
    sa.Column('phases', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'slug', name='uq_program_firm_slug')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_firm_id'), ['firm_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['trade_histories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('seed_ref', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('etag', sa.String(length=300), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('last_hash', sa.String(length=64), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'canonical_url', name='uq_source_firm_url')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_firm_id'), ['firm_id'], unique=False)

    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('account_size', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challenges_program_id'), ['program_id'], unique=False)

    op.create_table('document_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_snapshots_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_snapshots_source_id'), ['source_id'], unique=False)

    op.create_table('rule_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=300), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('old_doc_hash', sa.String(length=64), nullable=True),
    sa.Column('new_doc_hash', sa.String(length=64), nullable=True),
    sa.Column('diff_fragment', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('approval_state', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=80), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_changes_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_changes_rule_key'), ['rule_key'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=300), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('raw_params', sa.JSON(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('interpretation_status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('interpretation_notes', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=80), nullable=True),
    sa.Column('parser_version', sa.String(length=40), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_rule_key'), ['rule_key'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('fragment', sa.Text(), nullable=False),
    sa.Column('fragment_hash', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parser_version', sa.String(length=40), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['document_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_firm_id'), ['firm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_firm_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_rule_key'))
        batch_op.drop_index(batch_op.f('ix_rules_is_current'))
        batch_op.drop_index(batch_op.f('ix_rules_firm_id'))

    op.drop_table('rules')
    with op.batch_alter_table('rule_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_changes_rule_key'))
        batch_op.drop_index(batch_op.f('ix_rule_changes_firm_id'))

    op.drop_table('rule_changes')
    with op.batch_alter_table('document_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_snapshots_source_id'))
        batch_op.drop_index(batch_op.f('ix_document_snapshots_content_hash'))

    op.drop_table('document_snapshots')
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challenges_program_id'))

    op.drop_table('challenges')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_firm_id'))

    op.drop_table('sources')
    op.drop_table('recommendations')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_firm_id'))

    op.drop_table('programs')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_firm_id'))

    op.drop_table('conflicts')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    op.drop_table('wallet_addresses')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_version'))

    op.drop_table('user_profiles')
    op.drop_table('trading_accounts')
    op.drop_table('trade_histories')
    op.drop_table('settings')
    op.drop_table('risk_states')
    op.drop_table('processed_events')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_account_id'))

    op.drop_table('orders')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_input_hash'))

    op.drop_table('llm_calls')
    op.drop_table('ledger_positions')
    with op.batch_alter_table('kill_switches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kill_switches_account_id'))

    op.drop_table('kill_switches')
    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firms_slug'))

    op.drop_table('firms')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_kind'))
        batch_op.drop_index(batch_op.f('ix_audit_log_account_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
